# Generated by Django 6.1.1 on 2026-09-07 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_subject'),
        ('accounts', '0002_staffassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='staffassignment',
            constraint=models.UniqueConstraint(fields=('staff', 'subject'), name='unique_staff_subject'),
        ),
    ]
