# Generated by Django 6.1.1 on 2026-09-18 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_websitemenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_small_title', models.CharField(default='Welcome to EduManage College', max_length=200)),
                ('hero_title', models.CharField(default='Build Your Future With Quality Education', max_length=300)),
                ('hero_description', models.TextField(default='Discover knowledge, develop your skills, and build a successful career with us.')),
                ('hero_button_1_text', models.CharField(default='Apply Now', max_length=100)),
                ('hero_button_1_link', models.CharField(default='/admissions', max_length=200)),
                ('hero_button_2_text', models.CharField(default='Explore Courses', max_length=100)),
                ('hero_button_2_link', models.CharField(default='/courses', max_length=200)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='website/home/hero/')),
                ('about_label', models.CharField(default='About Our College', max_length=200)),
                ('about_title', models.CharField(default='Education That Creates Opportunities', max_length=300)),
                ('about_description_1', models.TextField(default='EduManage College provides quality education with modern learning facilities and experienced faculty members.')),
                ('about_description_2', models.TextField(default='Our goal is to help students develop academic knowledge, technical skills and professional confidence.')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='website/home/about/')),
                ('courses_label', models.CharField(default='Academic Programs', max_length=200)),
                ('courses_title', models.CharField(default='Our Popular Courses', max_length=300)),
                ('courses_description', models.TextField(default='Explore our undergraduate and postgraduate programs.')),
                ('admission_label', models.CharField(default='Admissions Open', max_length=200)),
                ('admission_title', models.CharField(default='Start Your College Journey Today', max_length=300)),
                ('admission_description', models.TextField(default='Applications are now open for the upcoming academic year.')),
                ('admission_button_text', models.CharField(default='Apply Now', max_length=100)),
                ('admission_button_link', models.CharField(default='/admissions', max_length=200)),
                ('offers_label', models.CharField(default='Scholarships & Offers', max_length=200)),
                ('offers_title', models.CharField(default='Special Opportunities', max_length=300)),
                ('departments_label', models.CharField(default='Academics', max_length=200)),
                ('departments_title', models.CharField(default='Our Departments', max_length=300)),
                ('why_label', models.CharField(default='Why EduManage', max_length=200)),
                ('why_title', models.CharField(default='Why Choose Our College?', max_length=300)),
                ('facilities_label', models.CharField(default='Campus', max_length=200)),
                ('facilities_title', models.CharField(default='Our Facilities', max_length=300)),
                ('events_label', models.CharField(default='Campus Life', max_length=200)),
                ('events_title', models.CharField(default='Upcoming Events', max_length=300)),
                ('notices_label', models.CharField(default='Updates', max_length=200)),
                ('notices_title', models.CharField(default='Latest News & Notices', max_length=300)),
                ('placement_label', models.CharField(default='Career & Placement', max_length=200)),
                ('placement_title', models.CharField(default='Build Your Career With Us', max_length=300)),
                ('placement_description', models.TextField(default='Connect with companies and explore career opportunities through our placement program.')),
                ('placement_button_text', models.CharField(default='Explore Placements', max_length=100)),
                ('placement_button_link', models.CharField(default='/placements', max_length=200)),
                ('gallery_label', models.CharField(default='Campus Life', max_length=200)),
                ('gallery_title', models.CharField(default='College Gallery', max_length=300)),
                ('testimonial_label', models.CharField(default='Student Experiences', max_length=200)),
                ('testimonial_title', models.CharField(default='What Our Students Say', max_length=300)),
                ('contact_label', models.CharField(default='Contact Us', max_length=200)),
                ('contact_title', models.CharField(default='Get In Touch With Us', max_length=300)),
                ('contact_description', models.TextField(default='Have questions about admissions, courses or our college?')),
                ('contact_address', models.CharField(default='Madurai, Tamil Nadu', max_length=300)),
                ('contact_phone', models.CharField(default='+91 XXXXX XXXXX', max_length=50)),
                ('contact_email', models.EmailField(default='college@example.com', max_length=254)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Page',
            },
        ),
        migrations.CreateModel(
            name='HomeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='🎓', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='accounts.homepage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='accounts.homepage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='website/home/gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='accounts.homepage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='website/home/facilities/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='accounts.homepage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='website/home/events/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.homepage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='💻', max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='accounts.homepage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='website/home/courses/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.homepage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='🎓', max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='accounts.homepage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('student', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='accounts.homepage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeWhyChoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='👨\u200d🏫', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='why_choose_us', to='accounts.homepage')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
