# Generated by Django 6.1.1 on 2026-09-19 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_homepage_homeoffer_homenotice_homegallery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_label', models.CharField(default='Academic Programs', max_length=200)),
                ('hero_title', models.CharField(default='Our Courses', max_length=200)),
                ('hero_description', models.TextField(blank=True)),
                ('intro_label', models.CharField(default='Academic Excellence', max_length=200)),
                ('intro_title', models.CharField(default='Find the Right Course for You', max_length=200)),
                ('intro_description', models.TextField(blank=True)),
                ('cta_title', models.CharField(default='Ready to Start Your Journey?', max_length=200)),
                ('cta_description', models.TextField(blank=True)),
                ('cta_button_text', models.CharField(default='Apply Now', max_length=100)),
                ('cta_button_link', models.CharField(default='/admissions', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CoursePageCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='accounts.coursepage')),
            ],
        ),
    ]
