# Generated by Django 6.1.1 on 2026-09-20 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_coursepage_coursepagecourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_label', models.CharField(default='About Us', max_length=200)),
                ('hero_title', models.CharField(default='About EduManage College', max_length=200)),
                ('hero_description', models.TextField(blank=True)),
                ('intro_label', models.CharField(default='Who We Are', max_length=200)),
                ('intro_title', models.CharField(default='Building Knowledge, Skills and Confidence', max_length=200)),
                ('intro_description_1', models.TextField(blank=True)),
                ('intro_description_2', models.TextField(blank=True)),
                ('intro_description_3', models.TextField(blank=True)),
                ('intro_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('direction_label', models.CharField(default='Our Direction', max_length=200)),
                ('direction_title', models.CharField(default='Vision & Mission', max_length=200)),
                ('vision_title', models.CharField(default='Our Vision', max_length=200)),
                ('vision_description', models.TextField(blank=True)),
                ('mission_title', models.CharField(default='Our Mission', max_length=200)),
                ('mission_description', models.TextField(blank=True)),
                ('values_label', models.CharField(default='Our Values', max_length=200)),
                ('values_title', models.CharField(default='What We Believe In', max_length=200)),
                ('facilities_label', models.CharField(default='Campus', max_length=200)),
                ('facilities_title', models.CharField(default='Our Facilities', max_length=200)),
                ('cta_label', models.CharField(default='Join Us', max_length=200)),
                ('cta_title', models.CharField(default='Start Your Academic Journey', max_length=200)),
                ('cta_description', models.TextField(blank=True)),
                ('cta_button_1_text', models.CharField(default='Explore Courses', max_length=100)),
                ('cta_button_1_link', models.CharField(default='/courses', max_length=200)),
                ('cta_button_2_text', models.CharField(default='Apply Now', max_length=100)),
                ('cta_button_2_link', models.CharField(default='/admissions', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/facilities/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='accounts.aboutpage')),
            ],
        ),
        migrations.CreateModel(
            name='AboutValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='🎓', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='accounts.aboutpage')),
            ],
        ),
    ]
