# Generated by Django 6.1.1 on 2026-09-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_aboutpage_aboutfacility_aboutvalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icon', models.CharField(default='💻', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteDepartmentsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_label', models.CharField(default='Departments', max_length=100)),
                ('hero_title', models.CharField(default='Our Departments', max_length=250)),
                ('hero_description', models.TextField(blank=True, default='Explore our academic departments and discover opportunities for learning, research and career growth.')),
                ('section_label', models.CharField(default='ACADEMICS', max_length=100)),
                ('section_title', models.CharField(default='Explore Our Academic Departments', max_length=250)),
                ('section_description', models.TextField(blank=True, default='Our departments provide quality education, practical learning and opportunities for students to develop their skills.')),
                ('cta_title', models.CharField(default='Find the Right Course for Your Future', max_length=250)),
                ('cta_description', models.TextField(blank=True, default='Explore our courses and choose the academic program that matches your career goals.')),
                ('cta_button_text', models.CharField(default='Explore Courses', max_length=100)),
                ('cta_button_link', models.CharField(default='/courses', max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Departments Page',
                'verbose_name_plural': 'Departments Page',
            },
        ),
    ]
