# Generated by Django 6.1.1 on 2026-09-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_websitedepartment_websitedepartmentspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteAdmissionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteAdmissionsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_label', models.CharField(default='Admissions', max_length=100)),
                ('hero_title', models.CharField(default='Start Your College Journey', max_length=250)),
                ('hero_description', models.TextField(blank=True, default='Learn about our admission process, requirements and opportunities.')),
                ('process_label', models.CharField(default='How It Works', max_length=100)),
                ('process_title', models.CharField(default='Admission Process', max_length=250)),
                ('requirements_label', models.CharField(default='Requirements', max_length=100)),
                ('requirements_title', models.CharField(default='Documents Required', max_length=250)),
                ('requirements_description', models.TextField(blank=True, default='Applicants may need to submit the following documents during the admission process.')),
                ('cta_title', models.CharField(default='Need Admission Assistance?', max_length=250)),
                ('cta_description', models.TextField(blank=True, default='Contact our admission team for more information.')),
                ('cta_button_text', models.CharField(default='Contact Us', max_length=100)),
                ('cta_button_link', models.CharField(default='/contact', max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admissions Page',
                'verbose_name_plural': 'Admissions Page',
            },
        ),
        migrations.CreateModel(
            name='WebsiteAdmissionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='01', max_length=20)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_label', models.CharField(default='Contact Us', max_length=100)),
                ('hero_title', models.CharField(default='Get In Touch With Us', max_length=250)),
                ('hero_description', models.TextField(blank=True, default='Have questions about admissions, courses or our college? Contact us.')),
                ('section_label', models.CharField(default='Contact Information', max_length=100)),
                ('section_title', models.CharField(default='We Would Love to Hear From You', max_length=250)),
                ('section_description', models.TextField(blank=True, default='Contact our college team for admissions, academic and general enquiries.')),
                ('address', models.TextField(blank=True, default='Madurai, Tamil Nadu, India')),
                ('phone', models.CharField(blank=True, default='+91 98765 43210', max_length=100)),
                ('email', models.EmailField(blank=True, default='info@edumanagecollege.com', max_length=254)),
                ('form_title', models.CharField(default='Send Us a Message', max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Page',
                'verbose_name_plural': 'Contact Page',
            },
        ),
        migrations.CreateModel(
            name='WebsiteEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='website/events/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteEventsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_label', models.CharField(default='Campus Life', max_length=100)),
                ('hero_title', models.CharField(default='Events & Activities', max_length=250)),
                ('hero_description', models.TextField(blank=True, default='Stay updated with college events, programs and activities.')),
                ('section_label', models.CharField(default="What's Happening", max_length=100)),
                ('section_title', models.CharField(default='Upcoming Events', max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Events Page',
                'verbose_name_plural': 'Events Page',
            },
        ),
        migrations.CreateModel(
            name='WebsiteGalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='website/gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteGalleryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_label', models.CharField(default='Campus Life', max_length=100)),
                ('hero_title', models.CharField(default='College Gallery', max_length=250)),
                ('hero_description', models.TextField(blank=True, default='Explore our campus, facilities, events and student activities.')),
                ('section_label', models.CharField(default='Our Memories', max_length=100)),
                ('section_title', models.CharField(default='Campus Gallery', max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Gallery Page',
                'verbose_name_plural': 'Gallery Page',
            },
        ),
    ]
