# Generated by Django 6.1.1 on 2026-09-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_websiteadmissiondocument_websiteadmissionspage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteNoticesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_label', models.CharField(default='Updates', max_length=100)),
                ('hero_title', models.CharField(default='Notices & Announcements', max_length=250)),
                ('hero_description', models.TextField(blank=True, default='Stay informed about the latest college announcements and updates.')),
                ('section_label', models.CharField(default='Latest Updates', max_length=100)),
                ('section_title', models.CharField(default='College Notices', max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notices Page',
                'verbose_name_plural': 'Notices Page',
            },
        ),
        migrations.CreateModel(
            name='WebsitePlacementFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='💼', max_length=50)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WebsitePlacementsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_label', models.CharField(default='Career & Placement', max_length=100)),
                ('hero_title', models.CharField(default='Build Your Career With Us', max_length=250)),
                ('hero_description', models.TextField(blank=True, default='Explore career development and placement opportunities available to our students.')),
                ('intro_label', models.CharField(default='Placement Support', max_length=100)),
                ('intro_title', models.CharField(default='Preparing Students for the Future', max_length=250)),
                ('intro_description_1', models.TextField(blank=True, default='Our placement activities help students develop technical knowledge, communication skills and professional confidence.')),
                ('intro_description_2', models.TextField(blank=True, default='Students can participate in training, career guidance and recruitment activities.')),
                ('intro_image', models.ImageField(blank=True, null=True, upload_to='website/placements/')),
                ('feature_label', models.CharField(default='Career Development', max_length=100)),
                ('feature_title', models.CharField(default='Placement Activities', max_length=250)),
                ('cta_title', models.CharField(default='Interested in Our Programs?', max_length=250)),
                ('cta_description', models.TextField(blank=True, default='Explore our courses and start preparing for your career.')),
                ('cta_button_text', models.CharField(default='Explore Courses', max_length=100)),
                ('cta_button_link', models.CharField(default='/courses', max_length=250)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Placements Page',
                'verbose_name_plural': 'Placements Page',
            },
        ),
    ]
