# Generated by Django 6.1.1 on 2026-09-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_websitedepartment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebsiteDepartment',
        ),
        migrations.AddField(
            model_name='department',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
