# Generated by Django 6.1.1 on 2026-09-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_subject'),
        ('students', '0002_student_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='examparticipation',
            constraint=models.UniqueConstraint(fields=('exam', 'student'), name='unique_exam_participation'),
        ),
    ]
