# Generated by Django 6.1.1 on 2026-09-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_examparticipation_unique_exam_participation'),
        ('reexams', '0001_initial'),
        ('students', '0002_student_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reexam',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddConstraint(
            model_name='reexam',
            constraint=models.UniqueConstraint(fields=('participation',), name='unique_participation_reexam'),
        ),
    ]
