# Generated by Django 6.1.1 on 2026-09-07 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_subject'),
        ('attendance', '0001_initial'),
        ('students', '0002_student_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_student_attendance_per_day',
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='academics.subject'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'date'), name='unique_student_subject_attendance_per_day'),
        ),
    ]
